name: zxbase_api_client
description: Zxbase Dart API client.
version: 1.1.3
homepage: https://zxbase.com
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  http: ^1.0.0
  uuid: ^4.0.0
  zxbase_crypto:
    git: https://github.com/zxbase/zxbase_crypto
  zxbase_model:
    git: https://github.com/zxbase/zxbase_model

dev_dependencies:
  lints: ^4.0.0
  test: ^1.0.0
