name: zxbase_api_client
description: Zxbase Dart API client.
version: 1.1.1
homepage: https://zxbase.com
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  http: ^1.0.0
  uuid: ^3.0.0
  zxbase_crypto:
    git: https://github.com/zxbase/zxbase_crypto
  zxbase_model:
    git: https://github.com/zxbase/zxbase_model

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
