name: Dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deps:
    name: Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Check outdated dependencies
        run: ./tool/dependencies
